# Generated by Django 5.2.7 on 2025-12-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadgen_id', models.CharField(max_length=100, unique=True)),
                ('created_time', models.DateTimeField()),
                ('ad_id', models.CharField(max_length=50)),
                ('ad_name', models.CharField(max_length=200)),
                ('adset_id', models.CharField(max_length=50)),
                ('adset_name', models.CharField(max_length=200)),
                ('campaign_id', models.CharField(max_length=50)),
                ('campaign_name', models.CharField(max_length=200)),
                ('form_id', models.CharField(max_length=50)),
                ('form_name', models.CharField(max_length=200)),
                ('is_organic', models.BooleanField(default=False)),
                ('platform', models.CharField(max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_fields', models.JSONField(default=dict)),
                ('raw_payload', models.JSONField(default=dict)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
