# Generated by Django 5.2.7 on 2026-02-04 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0017_alter_cita_estatus_seguimiento_alter_cita_lugar_and_more'),
        ('leads', '0002_metaleadfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metaleadfield',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='metalead',
            name='cita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_lead', to='comercial.cita'),
        ),
        migrations.AddField(
            model_name='metalead',
            name='cita_agendada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metalead',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='metalead',
            name='contactado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metalead',
            name='estatus',
            field=models.CharField(blank=True, choices=[('Perdido', 'Perdido'), ('No calificado', 'No calificado'), ('Calificado', 'Calificado'), ('Convertido', 'Convertido')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='metalead',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='metalead',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metalead',
            name='servicio',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Auditoría Contable', 'Auditoría Contable'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('E-Commerce', 'E-Commerce'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Materialidad', 'Materialidad'), ('Reclutamiento', 'Reclutamiento'), ('REPSE', 'REPSE')], max_length=100, null=True),
        ),
    ]
