# Generated by Django 5.2.7 on 2026-02-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_metaleadfield_options_metalead_cita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metalead',
            name='form_name',
        ),
        migrations.AlterField(
            model_name='metalead',
            name='servicio',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Auditoría Contable', 'Auditoría Contable'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('CUSTOMEER', 'CUSTOMEER'), ('Control operativo', 'Control operativo'), ('E-Commerce', 'E-Commerce'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Materialidad', 'Materialidad'), ('Reclutamiento', 'Reclutamiento'), ('REPSE', 'REPSE')], max_length=100, null=True),
        ),
    ]
