# Generated by Django 5.2.7 on 2026-02-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_remove_metalead_form_name_alter_metalead_servicio"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MetaLeadField",
        ),
    ]
