# Generated by Django 5.2.7 on 2026-02-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_remove_metaleadfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedInLead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lead_id", models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ("created_time", models.DateTimeField(blank=True, null=True)),
                ("ad_id", models.CharField(blank=True, max_length=80, null=True)),
                ("ad_name", models.CharField(blank=True, max_length=200, null=True)),
                ("adset_id", models.CharField(blank=True, max_length=80, null=True)),
                ("adset_name", models.CharField(blank=True, max_length=200, null=True)),
                ("campaign_id", models.CharField(blank=True, max_length=80, null=True)),
                ("campaign_name", models.CharField(blank=True, max_length=200, null=True)),
                ("form_id", models.CharField(blank=True, max_length=80, null=True)),
                ("platform", models.CharField(default="linkedin", max_length=50)),
                ("full_name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=50, null=True)),
                ("job_title", models.CharField(blank=True, max_length=150, null=True)),
                ("company_name", models.CharField(blank=True, max_length=200, null=True)),
                ("contactado", models.BooleanField(default=False)),
                ("estatus", models.CharField(blank=True, choices=[("Perdido", "Perdido"), ("No calificado", "No calificado"), ("Calificado", "Calificado"), ("Convertido", "Convertido")], max_length=30, null=True)),
                ("servicio", models.CharField(blank=True, choices=[("Pendiente", "Pendiente"), ("AuditorÃ­a Contable", "AuditorÃ­a Contable"), ("Contabilidad", "Contabilidad"), ("Corridas", "Corridas"), ("CUSTOMEER", "CUSTOMEER"), ("Control operativo", "Control operativo"), ("E-Commerce", "E-Commerce"), ("Laboral", "Laboral"), ("Maquila de NÃ³mina", "Maquila de NÃ³mina"), ("Marketing", "Marketing"), ("Materialidad", "Materialidad"), ("Reclutamiento", "Reclutamiento"), ("REPSE", "REPSE")], max_length=100, null=True)),
                ("cita_agendada", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True, null=True)),
                ("raw_fields", models.JSONField(default=dict)),
                ("raw_payload", models.JSONField(default=dict)),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("cita", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="linkedin_lead", to="comercial.cita")),
            ],
        ),
    ]
