# Generated by Django 5.2.7 on 2025-12-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades_merca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadmerca',
            name='area',
            field=models.CharField(choices=[('Análisis de Mkt', 'Análisis de Mkt'), ('Blog', 'Blog'), ('Branding', 'Branding'), ('Campañas', 'Campañas'), ('Capacitación y/o juntas', 'Capacitación y/o juntas'), ('Comercialización', 'Comercialización'), ('Extras', 'Extras'), ('Internas', 'Internas'), ('Página Web Diseño/Mtto', 'Página Web Diseño/Mtto'), ('Parrilla', 'Parrilla'), ('Performance Mkt', 'Performance Mkt'), ('Reportes', 'Reportes'), ('Vídeos', 'Vídeos')], max_length=100),
        ),
        migrations.AlterField(
            model_name='actividadmerca',
            name='disenador',
            field=models.CharField(blank=True, choices=[('Leo G.', 'Leo G.'), ('Luis F.', 'Luis F.'), ('Sabine G.', 'Sabine G.'), ('Todos', 'Todos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actividadmerca',
            name='mercadologo',
            field=models.CharField(blank=True, choices=[('Alan S.', 'Alan S.'), ('Paty L.', 'Paty L.'), ('Todos', 'Todos')], max_length=100, null=True),
        ),
    ]
