# Generated by Django 5.2.7 on 2025-12-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades_merca', '0003_actividadmerca_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadmerca',
            name='tarea',
            field=models.CharField(max_length=1000),
        ),
    ]
