# Generated by Django 5.2.7 on 2026-01-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades_merca', '0004_alter_actividadmerca_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadmerca',
            name='mercadologo',
            field=models.CharField(blank=True, choices=[('Aldo S.', 'Aldo S.'), ('Paty L.', 'Paty L.'), ('Todos', 'Todos')], max_length=100, null=True),
        ),
    ]
