# Generated by Django 5.2.7 on 2026-02-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades_merca', '0006_actividadmerca_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadmerca',
            name='area',
            field=models.CharField(choices=[('Análisis de Mkt', 'Análisis de Mkt'), ('Blog', 'Blog'), ('Branding', 'Branding'), ('Campañas', 'Campañas'), ('Capacitación y/o juntas', 'Capacitación y/o juntas'), ('Comercialización', 'Comercialización'), ('Extras', 'Extras'), ('Internas', 'Internas'), ('Página Web Diseño/Mtto', 'Página Web Diseño/Mtto'), ('Parrilla', 'Parrilla'), ('Performance Mkt', 'Performance Mkt'), ('Vídeos', 'Vídeos')], max_length=100),
        ),
    ]
