# Generated by Django 5.2.7 on 2025-12-23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActividadExp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tarea", models.CharField(max_length=200)),
                ("tipo", models.CharField(choices=[("Cliente Arau", "Cliente Arau"), ("Colaboradores", "Colaboradores")], max_length=50)),
                ("area", models.CharField(choices=[("Experiencia", "Experiencia"), ("Mercadotecnia", "Mercadotecnia"), ("Administración", "Administración"), ("Operaciones", "Operaciones"), ("Contabilidad", "Contabilidad"), ("Comercial", "Comercial"), ("Reclutamiento", "Reclutamiento"), ("Legal", "Legal"), ("Fiscal", "Fiscal"), ("Enrok", "Enrok")], max_length=50)),
                ("estilo", models.CharField(choices=[("Texto", "Texto"), ("Imagen", "Imagen")], max_length=50)),
                ("fecha_solicitud_exp", models.DateField(blank=True, null=True)),
                ("fecha_solicitud_mkt", models.DateField(blank=True, null=True)),
                ("fecha_entrega_mkt", models.DateField(blank=True, null=True)),
                ("comunicado_aviso", models.CharField(choices=[("Programado", "Programado"), ("Especial", "Especial")], max_length=50)),
                ("url", models.URLField(blank=True, null=True)),
                ("estatus_envio", models.BooleanField(default=False)),
                ("fecha_envio", models.DateField(blank=True, null=True)),
                ("notas", models.TextField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Actividad Exp",
                "verbose_name_plural": "Actividades Exp",
                "ordering": ["-fecha_solicitud_exp", "-creado"],
            },
        ),
    ]
