# Generated by Django 5.2.7 on 2025-12-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actividades_exp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividadexp",
            name="area",
            field=models.CharField(blank=True, choices=[("Experiencia", "Experiencia"), ("Mercadotecnia", "Mercadotecnia"), ("Administración", "Administración"), ("Operaciones", "Operaciones"), ("Contabilidad", "Contabilidad"), ("Comercial", "Comercial"), ("Reclutamiento", "Reclutamiento"), ("Legal", "Legal"), ("Fiscal", "Fiscal"), ("Enrok", "Enrok")], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="actividadexp",
            name="comunicado_aviso",
            field=models.CharField(blank=True, choices=[("Programado", "Programado"), ("Especial", "Especial")], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="actividadexp",
            name="estilo",
            field=models.CharField(blank=True, choices=[("Texto", "Texto"), ("Imagen", "Imagen")], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="actividadexp",
            name="tarea",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="actividadexp",
            name="tipo",
            field=models.CharField(blank=True, choices=[("Cliente Arau", "Cliente Arau"), ("Colaboradores", "Colaboradores")], max_length=50, null=True),
        ),
    ]
