# Generated by Django 5.2.7 on 2025-12-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_useractionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersessionactivity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
