# Generated by Django 5.2.7 on 2025-12-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_usersessionactivity_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersessionactivity",
            name="last_action",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="usersessionactivity",
            name="last_method",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="usersessionactivity",
            name="last_path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
