# Generated by Django 5.2.7 on 2025-11-28 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alianzas', '0002_alter_alianza_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alianza',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono debe tener exactamente 10 dígitos.')]),
        ),
    ]
