# Generated by Django 5.2.7 on 2025-12-02 21:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0007_cliente_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('servicio', models.CharField(max_length=50)),
                ('facturadora', models.CharField(blank=True, max_length=100, null=True)),
                ('num_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('monto_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comision_porcentaje', models.DecimalField(decimal_places=4, editable=False, max_digits=7)),
                ('monto_comision', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('comentarios', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
