# Generated by Django 5.2.7 on 2025-12-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_arranque',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
