# Generated by Django 5.2.7 on 2025-12-22 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0003_sync_estatus_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienciacliente',
            name='estatus_cliente',
        ),
    ]
