# Generated by Django 5.2.7 on 2025-12-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0004_remove_experienciacliente_estatus_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienciacliente',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='experienciacliente',
            name='estatus',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Pausa', 'Pausa'), ('Baja', 'Baja'), ('Reingreso', 'Reingreso')], max_length=20, null=True),
        ),
    ]
