# Generated by Django 5.2.7 on 2025-12-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0005_remove_experienciacliente_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienciacliente',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='experienciacliente',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='experienciacliente',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='experienciacliente',
            name='telefono',
        ),
    ]
