# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiencia", "0006_remove_experienciacliente_contacto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experienciacliente",
            name="propuesta",
            field=models.URLField(blank=True, null=True, verbose_name="Propuesta"),
        ),
    ]
