# Generated by Django 5.2.7 on 2025-11-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospecto', models.CharField(max_length=150)),
                ('giro', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo', models.CharField(blank=True, max_length=150, null=True)),
                ('medio', models.CharField(blank=True, max_length=150, null=True)),
                ('servicio', models.CharField(blank=True, max_length=150, null=True)),
                ('contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('conexion', models.CharField(blank=True, max_length=150, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=150, null=True)),
                ('estatus_cita', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_cita', models.DateTimeField()),
                ('numero_cita', models.CharField(blank=True, max_length=150, null=True)),
                ('estatus_seguimiento', models.CharField(blank=True, max_length=150, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
