# Generated by Django 5.2.7 on 2025-11-04 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha_cita'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterField(
            model_name='cita',
            name='estatus_cita',
            field=models.CharField(blank=True, choices=[('Agendada', 'Agendada'), ('Pospuesta', 'Pospuesta'), ('Cancelada', 'Cancelada'), ('Atendida', 'Atendida')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='lugar',
            field=models.CharField(blank=True, choices=[('Arau', 'Arau'), ('Zoom', 'Zoom'), ('Oficina del cliente', 'Oficina del cliente')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='medio',
            field=models.CharField(blank=True, choices=[('Remarketing', 'Remarketing'), ('Alianzas', 'Alianzas'), ('Lead', 'Lead'), ('Procompite', 'Procompite'), ('Ejecutivos', 'Ejecutivos'), ('Personales', 'Personales'), ('Expos / Eventos Deportivos', 'Expos / Eventos Deportivos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='numero_cita',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(blank=True, choices=[('Auditoría Contable', 'Auditoría Contable'), ('Auditoría Fiscal', 'Auditoría Fiscal'), ('Auto Ahorro', 'Auto Ahorro'), ('CheckUp', 'CheckUp'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('E-Commerce', 'E-Commerce'), ('Fiscal', 'Fiscal'), ('Hidrocarburos', 'Hidrocarburos'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Monederos', 'Monederos'), ('PRAIDS', 'PRAIDS'), ('PROCOM', 'PROCOM'), ('Reclutamiento', 'Reclutamiento'), ('TPV', 'TPV'), ('Valuación de Activos Intangibles', 'Valuación de Activos Intangibles'), ('Venta de empresa', 'Venta de empresa'), ('VP360°', 'VP360°'), ('Préstamo', 'Préstamo'), ('Reembolso', 'Reembolso')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono debe tener exactamente 10 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Producto', 'Producto'), ('Servicio', 'Servicio')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='vendedor',
            field=models.CharField(blank=True, choices=[('Giovanni', 'Giovanni'), ('Daniel S.', 'Daniel S.')], max_length=50, null=True),
        ),
    ]
