# Generated by Django 5.2.7 on 2025-11-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_alter_cita_estatus_seguimiento_alter_cita_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='servicio2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='lugar',
            field=models.CharField(blank=True, choices=[('Oficina de Arau', 'Oficina de Arau'), ('Oficina del cliente', 'Oficina del cliente'), ('Zoom', 'Zoom')], max_length=50, null=True),
        ),
    ]
