# Generated by Django 5.2.7 on 2025-11-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_cita_servicio2_cita_servicio3_alter_cita_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='servicio2',
            field=models.CharField(blank=True, choices=[('Auditoría Contable', 'Auditoría Contable'), ('Auditoría Fiscal', 'Auditoría Fiscal'), ('Auto Ahorro', 'Auto Ahorro'), ('CheckUp', 'CheckUp'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('E-Commerce', 'E-Commerce'), ('Fiscal', 'Fiscal'), ('Hidrocarburos', 'Hidrocarburos'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Monederos', 'Monederos'), ('PRAIDS', 'PRAIDS'), ('PROCOM', 'PROCOM'), ('Reclutamiento', 'Reclutamiento'), ('TPV', 'TPV'), ('Valuación de Activos Intangibles', 'Valuación de Activos Intangibles'), ('Venta de empresa', 'Venta de empresa'), ('VP360°', 'VP360°'), ('Préstamo', 'Préstamo'), ('Reembolso', 'Reembolso')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio3',
            field=models.CharField(blank=True, choices=[('Auditoría Contable', 'Auditoría Contable'), ('Auditoría Fiscal', 'Auditoría Fiscal'), ('Auto Ahorro', 'Auto Ahorro'), ('CheckUp', 'CheckUp'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('E-Commerce', 'E-Commerce'), ('Fiscal', 'Fiscal'), ('Hidrocarburos', 'Hidrocarburos'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Monederos', 'Monederos'), ('PRAIDS', 'PRAIDS'), ('PROCOM', 'PROCOM'), ('Reclutamiento', 'Reclutamiento'), ('TPV', 'TPV'), ('Valuación de Activos Intangibles', 'Valuación de Activos Intangibles'), ('Venta de empresa', 'Venta de empresa'), ('VP360°', 'VP360°'), ('Préstamo', 'Préstamo'), ('Reembolso', 'Reembolso')], max_length=100, null=True),
        ),
    ]
