# Generated by Django 5.2.7 on 2025-11-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_alter_cita_servicio2_alter_cita_servicio3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='monto_factura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estatus_seguimiento',
            field=models.CharField(blank=True, choices=[('Esperando respuesta del cliente', 'Esperando respuesta del cliente'), ('Agendar nueva cita', 'Agendar nueva cita'), ('Solicitud de propuesta', 'Solicitud de propuesta'), ('Elaboración de propuesta', 'Elaboración de propuesta'), ('Propuesta enviada', 'Propuesta enviada'), ('Se envió auditoría Laboral', 'Se envió auditoría Laboral'), ('Stand by', 'Stand by'), ('Pendiente de cierre', 'Pendiente de cierre'), ('En activación', 'En activación'), ('Cerrado', 'Cerrado'), ('No está interesado en este servicio', 'No está interesado en este servicio'), ('Fuera de su presupuesto', 'Fuera de su presupuesto')], max_length=100, null=True),
        ),
    ]
