# Generated by Django 5.2.7 on 2025-11-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_cita_monto_factura_alter_cita_estatus_seguimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='monto_factura',
        ),
        migrations.AlterField(
            model_name='cita',
            name='estatus_seguimiento',
            field=models.CharField(blank=True, choices=[('Esperando respuesta del cliente', 'Esperando respuesta del cliente'), ('Agendar nueva cita', 'Agendar nueva cita'), ('Solicitud de propuesta', 'Solicitud de propuesta'), ('Elaboración de propuesta', 'Elaboración de propuesta'), ('Propuesta enviada', 'Propuesta enviada'), ('Se envió auditoría Laboral', 'Se envió auditoría Laboral'), ('Stand by', 'Stand by'), ('Pendiente de cierre', 'Pendiente de cierre'), ('En activación', 'En activación'), ('Reclutando', 'Reclutando'), ('Cerrado', 'Cerrado'), ('No está interesado en este servicio', 'No está interesado en este servicio'), ('Fuera de su presupuesto', 'Fuera de su presupuesto')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='medio',
            field=models.CharField(blank=True, choices=[('Apollo', 'Apollo'), ('Remarketing', 'Remarketing'), ('Alianzas', 'Alianzas'), ('Lead', 'Lead'), ('Procompite', 'Procompite'), ('Ejecutivos', 'Ejecutivos'), ('Personales', 'Personales'), ('Expos / Eventos Deportivos', 'Expos / Eventos Deportivos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Auditoría Contable', 'Auditoría Contable'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('E-Commerce', 'E-Commerce'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Reclutamiento', 'Reclutamiento')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio2',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Auditoría Contable', 'Auditoría Contable'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('E-Commerce', 'E-Commerce'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Reclutamiento', 'Reclutamiento')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio3',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Auditoría Contable', 'Auditoría Contable'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('E-Commerce', 'E-Commerce'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Reclutamiento', 'Reclutamiento')], max_length=100, null=True),
        ),
    ]
