# Generated by Django 5.2.7 on 2025-11-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_remove_cita_monto_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='medio',
            field=models.CharField(choices=[('Apollo', 'Apollo'), ('Remarketing', 'Remarketing'), ('Alianzas', 'Alianzas'), ('Lead', 'Lead'), ('Procompite', 'Procompite'), ('Ejecutivos', 'Ejecutivos'), ('Personales', 'Personales'), ('Expos / Eventos Deportivos', 'Expos / Eventos Deportivos')], default='Leads', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Auditoría Contable', 'Auditoría Contable'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('E-Commerce', 'E-Commerce'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Reclutamiento', 'Reclutamiento')], default='Contabilidad', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='vendedor',
            field=models.CharField(choices=[('Giovanni', 'Giovanni'), ('Daniel S.', 'Daniel S.')], default='Giovanni', max_length=50),
            preserve_default=False,
        ),
    ]
