# Generated by Django 5.2.7 on 2025-11-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_alter_cita_medio_alter_cita_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Auditoría Contable', 'Auditoría Contable'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('E-Commerce', 'E-Commerce'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Reclutamiento', 'Reclutamiento'), ('REPSE', 'REPSE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio2',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Auditoría Contable', 'Auditoría Contable'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('E-Commerce', 'E-Commerce'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Reclutamiento', 'Reclutamiento'), ('REPSE', 'REPSE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio3',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Auditoría Contable', 'Auditoría Contable'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('E-Commerce', 'E-Commerce'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Reclutamiento', 'Reclutamiento'), ('REPSE', 'REPSE')], max_length=100, null=True),
        ),
    ]
