# Generated by Django 5.2.7 on 2025-11-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_alter_cita_servicio_alter_cita_servicio2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='numero_cita',
            field=models.CharField(blank=True, choices=[('Primera', 'Primera'), ('Segunda', 'Segunda'), ('Tercera', 'Tercera'), ('Cuarta', 'Cuarta'), ('Quinta', 'Quinta')], max_length=10, null=True),
        ),
    ]
