# Generated by Django 5.2.7 on 2026-01-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0014_cita_propuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='lugar',
            field=models.CharField(blank=True, choices=[('Oficina de Arau', 'Oficina de Arau'), ('Oficina del cliente', 'Oficina del cliente'), ('Zoom', 'Zoom'), ('Teléfono', 'Teléfono'), ('Correo', 'Correo')], max_length=50, null=True),
        ),
    ]
