# Generated by Django 5.2.7 on 2026-02-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0016_comercial_kpis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estatus_seguimiento',
            field=models.CharField(blank=True, choices=[('Esperando respuesta del cliente', 'Esperando respuesta del cliente'), ('Agendar nueva cita', 'Agendar nueva cita'), ('Solicitud de propuesta', 'Solicitud de propuesta'), ('ElaboraciÃ³n de propuesta', 'ElaboraciÃ³n de propuesta'), ('Propuesta enviada', 'Propuesta enviada'), ('Se enviÃ³ auditorÃ\xada Laboral', 'Se enviÃ³ auditorÃ\xada Laboral'), ('Stand by', 'Stand by'), ('Pendiente de cierre', 'Pendiente de cierre'), ('En activaciÃ³n', 'En activaciÃ³n'), ('Reclutando', 'Reclutando'), ('Cerrado', 'Cerrado'), ('No estÃ¡ interesado en este servicio', 'No estÃ¡ interesado en este servicio'), ('Fuera de su presupuesto', 'Fuera de su presupuesto')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='lugar',
            field=models.CharField(blank=True, choices=[('Oficina de Arau', 'Oficina de Arau'), ('Oficina del cliente', 'Oficina del cliente'), ('Zoom', 'Zoom'), ('TelÃ©fono', 'TelÃ©fono'), ('Correo', 'Correo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Auditoría Contable', 'Auditoría Contable'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('E-Commerce', 'E-Commerce'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Materialidad', 'Materialidad'), ('Reclutamiento', 'Reclutamiento'), ('REPSE', 'REPSE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio2',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Auditoría Contable', 'Auditoría Contable'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('E-Commerce', 'E-Commerce'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Materialidad', 'Materialidad'), ('Reclutamiento', 'Reclutamiento'), ('REPSE', 'REPSE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio3',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Auditoría Contable', 'Auditoría Contable'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('E-Commerce', 'E-Commerce'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Materialidad', 'Materialidad'), ('Reclutamiento', 'Reclutamiento'), ('REPSE', 'REPSE')], max_length=100, null=True),
        ),
    ]
