# Generated by Django 5.2.7 on 2025-12-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_cliente_total_comisiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='medio',
            field=models.CharField(blank=True, choices=[('Alianzas', 'Alianzas'), ('Apollo', 'Apollo'), ('Ejecutivos', 'Ejecutivos'), ('Expos / Eventos Deportivos', 'Expos / Eventos Deportivos'), ('Lead', 'Lead'), ('Personales', 'Personales'), ('Procompite', 'Procompite'), ('Remarketing', 'Remarketing')], max_length=100, null=True, verbose_name='Medio'),
        ),
    ]
