# Generated by Django 5.2.7 on 2025-12-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
    ]
