# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0013_cliente_campos_contacto"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="propuesta",
            field=models.URLField(blank=True, null=True, verbose_name="Propuesta"),
        ),
    ]
