# Generated by Django 5.2.7 on 2026-02-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_cliente_propuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='servicio',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Auditoría Contable', 'Auditoría Contable'), ('Contabilidad', 'Contabilidad'), ('Corridas', 'Corridas'), ('E-Commerce', 'E-Commerce'), ('Laboral', 'Laboral'), ('Maquila de Nómina', 'Maquila de Nómina'), ('Marketing', 'Marketing'), ('Materialidad', 'Materialidad'), ('Reclutamiento', 'Reclutamiento'), ('REPSE', 'REPSE')], max_length=100, null=True),
        ),
    ]
