# Generated by Django 5.2.7 on 2025-12-02 21:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alianzas', '0003_alter_alianza_telefono'),
        ('clientes', '0007_cliente_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_mes', models.IntegerField()),
                ('periodo_anio', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=50)),
                ('porcentaje', models.DecimalField(decimal_places=6, max_digits=9)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periodo_mes', models.IntegerField()),
                ('periodo_anio', models.IntegerField()),
                ('liberable_desde', models.DateField()),
                ('liberada', models.BooleanField(default=False)),
                ('estatus_pago_dispersion', models.CharField(max_length=50)),
                ('fecha_dispersion', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('comisionista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alianzas.alianza')),
            ],
        ),
    ]
