# Generated by Django 5.2.7 on 2025-12-02 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alianzas', '0003_alter_alianza_telefono'),
        ('comisiones', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='comisionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_comision', to='alianzas.alianza'),
        ),
    ]
