# Generated by Django 5.2.7 on 2025-12-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comisiones", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comision",
            name="pago_comision",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pagocomision",
            name="comision",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="pagos", to="comisiones.comision"),
        ),
    ]
